// Generated by CoffeeScript 1.7.1
(function() {
  var generateChart;

  generateChart = function() {
    var height, margin, outerHeight, outerWidth, svg, width, xAxis, xMap, xScale, xValue, yAxis, yMap, yScale, yValue;
    processData(true);
    $("svg").remove();
    margin = {
      top: 10,
      right: 10,
      bottom: 35,
      left: 50
    };
    width = 960 - margin.left - margin.right;
    height = 530 - margin.top - margin.bottom;
    xValue = function(d) {
      return d[0];
    };
    xScale = d3.scale.linear().domain([0, 14]).range([0, width]);
    xMap = function(d) {
      return xScale(xValue(d));
    };
    xAxis = d3.svg.axis().scale(xScale).orient("bottom").ticks(24).tickFormat(function(tick) {
      var hour;
      hour = tick + Math.floor(midnight_seconds / 3600);
      return hour % 24;
    });
    yValue = function(d) {
      return d[1];
    };
    yScale = d3.scale.linear().domain([0, 75]).range([height, 0]);
    yMap = function(d) {
      return yScale(yValue(d));
    };
    yAxis = d3.svg.axis().scale(yScale).orient("left").ticks(3);
    outerWidth = width + margin.left + margin.right;
    outerHeight = height + margin.top + margin.bottom;
    svg = d3.select("#container").append("svg").attr({
      width: "100%",
      height: "100%",
      id: "chart",
      viewBox: "0 0 " + outerWidth + " " + outerHeight,
      preserveAspectRatio: "xMidYMid meet"
    }).style({
      background: "rgb(30, 30, 30)",
      "max-height": "480"
    }).append("g").attr("transform", "translate(" + margin.left + ", " + margin.top + ")");

    svg.append("g").attr("class", "x axis").attr("transform", "translate(0, " + height + ")").call(xAxis).append("text").attr("class", "label").attr("x", width / 2).attr("y", 30).style("text-anchor", "end").text("Hour");

    svg.append("g").attr("class", "y axis").call(yAxis).append("text").attr("class", "label").attr("transform", "rotate(-90)").attr("x", -(height / 2.75)).attr("y", -30).style("text-anchor", "end").text("Work Efficiency");

    svg.append("g").selectAll("circle").data(past_chart_data).enter().append("circle").attr({
      cx: xMap,
      cy: yMap,
      r: 3.5
    }).style("opacity", 0.1).style("fill", "#0199FE");

    svg.append("g").selectAll("circle").data(today_chart_data).enter().append("circle").attr({
      cx: xMap,
      cy: yMap,
      r: 3
    }).style("fill", "#6a6").style("opacity", 0.4);

    svg.append("text").attr("class", "pr").attr("x", 800).attr("y", 90).text(today_percentile.toFixed(0));

    return svg.append("text").attr("id", "pf_timer_today_total").attr("x", 750).attr("y", 40).text("Test");
  };

  $(function() {
    checkCurrentDay();
    generateChart();
    updateWorkTime();
    setTimeout((function() {
      return location.reload(true);
    }), 30 * 1000);
  });

}).call(this);
